### ISSUE TITLE
Refactor open ephys package

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-mapper#104]
# User story
As a developer, I want each of the packages in the metadata-mapper to have a JobSettings. 

# Acceptance criteria
- [x] Create a module for models in the open_ephys package
- [x] Create a JobSettings class that inherits BaseJobSettings in new module
- [x] Move the parameters currently being inputted into the ETL to JobSettings, and add a Literal field job_settings_name 
- [ ] Pass job_settings to ETL and refactor ETL methods to retrieve info from job_settings
- [ ] Add OpenEphysJobSettings to SessionJobSettings Union in models.py

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
Look at bergamo package as example

**Comment by mekhlakapoor** [comment]
Arjun's going to work on this!

**Comment by arjunsridhar12345** [comment]
working

**Comment by mekhlakapoor** [comment]
Closing this issue as completed. Carter's refactor in #174 finished the first few criteria, and there's a new issue for the remaining part (adding it to GatherMetadata job #176)
