### ISSUE TITLE
create Session from openephys logs

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-mapper#14]
SashaB prototyped some code to automatically create a `Session` from OpenEphys log files. Let's integrate it here so that it can be run automatically.

reference code is here: https://codeocean.allenneuraldynamics.org/capsule/1630654/tree

**Comment by jtyoung84** [comment]
We need to figure out what's going to be SLIMS

**Comment by micahwoodard** [comment]
josh segal

**Comment by jtyoung84** [comment]
Start a thread on MS Teams

**Comment by micahwoodard** [comment]
pyqt gui to enter info for all the probes, rig.json has info about all the probes, start and stop time, location of arc and what probes are targeting which brain regoin, before session is started, enter in info, after finish point to directory and fill in relevant information, hannah lacodina and meghan olsen,
