### ISSUE TITLE
Refactor JobSettings into CamstimEphys class

### ISSUE THREAD

**Issue by rcpeene** [AllenNeuralDynamics/aind-metadata-mapper#165]
In order for @jtyoung84 to be able to automatically run metadata mapper in upload transfer service, the classes to generate the session json must be able to take JobSettings input. I should make this change to the CamstimEphys class.

More specifically, I ought to;

- Make new submodule for CamstimEphys which includes the pydantic model for JobSettings (can probably be taken from one of the existing classes?)
- Ensure GeneritcEtl uses the model to parse job settings
- Make CamstimEphys class inherit from GenericEtl and parse job settings

**Comment by mekhlakapoor** [comment]
Closed by PR #174
