### ISSUE TITLE
Mapper that maps ophys metadata files to session.json files

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-mapper#19]
# User story
As a user, I want to run a script that parses bonsai generated files, etc., into a session.json file that is valid under aind-data-schema so I can automatically generate and attach session.json files to my session.

# Acceptance criteria
- [ ] Maps to the latest version of aind-data-schema
- [ ] Given a user has some generated files from bonsai and other acquisition hardware, when they run a command from bash with some arguments for an input directory and an output directory, then a session.json file will be generated.
- [ ] 100% test and docstring coverage

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
- likely we should update whatever scripts Kenta runs on his rig to import and run the new mapper.

**Comment by dyf** [comment]
@mekhlakapoor made a first pass at this several months ago, but it's out of date now that `aind-data-schema` has changed:

https://github.com/AllenNeuralDynamics/Ophys_SensorScreening_ExperimetalControl/blob/main/src/schema_writer.py

You could start here make it work with the latest version of `aind-data-schema`.

**Comment by dyf** [comment]
And here is an example of a dummy fiber photometry session that may give you a sense of what the new schema is shaped like.
https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/examples/ophys_session.py
