### ISSUE TITLE
Add a rig etl for slims

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-metadata-mapper#208]
# User story
As an end user, I want to be able to fetch rig metadata from slims given a full or partial rig id, so I can add a rig and use rig-related etls or so that a downstream process can do this on upload of raw data

# Acceptance criteria
- [ ] This is something that can be verified to show that this user story is satisfied.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
- For the dynamic routing project, the full rig metadata rig_id may not be known at runtime so the partial matching id part is particularly important

**Comment by mekhlakapoor** [comment]
We have this in the metadata-service to fetch rigs from SLIMS. Maybe this request for an ETL to upload rigs should go there as well.

**Comment by mochic** [comment]
Our feature needs are already supported by aind-metadata-service. The partial matching may be added there in the future.
