### ISSUE TITLE
Upgrade data-schema

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-mapper#37]
# User story
As a user, I want the latest models from the data-schema

# Acceptance criteria
- [ ] Upgrade data-schema version
- [ ] Handle any necessary mapping updates

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mochic** [comment]
@mekhlakapoor I've upgraded the aind-data-schema to 0.31.17 in #38

**Comment by mekhlakapoor** [comment]
closing because duplicate ticket #39
