### ISSUE TITLE
pin aind-data-schema to newer version & update tests

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-metadata-mapper#39]
New mapper elements require updated versions of `aind-data-schema` to function.

Please update to `aind-data-schema==0.31.11` or newer for @Sun-flow 's needs.

@mekhlakapoor also has needs for this update, so check with her on what version she requires as well.

**Comment by mekhlakapoor** [comment]
This is a duplicate ticket and @mochic started working on it? look at this thread: #37

**Comment by jtyoung84** [comment]
Closed by https://github.com/AllenNeuralDynamics/aind-metadata-mapper/pull/40
