### ISSUE TITLE
Migrate fiber photometry metadata conversion script

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-mapper#4]
Acceptance criteria:
- existing conversion methods move to this repo
- update [Kenta's existing repo](https://github.com/AllenNeuralDynamics/Ophys_SensorScreening_ExperimetalControl) to import and utilize this repo
- put the utility methods in `fip.py`.
- there is one module for extracting metadata from files.
- there is an example script showing how into create a Session from those files.

**Comment by dyf** [comment]
@mekhlakapoor  is this already done?

**Comment by mekhlakapoor** [comment]
Yes, I think @micahwoodard did it in this PR: https://github.com/AllenNeuralDynamics/aind-metadata-mapper/pull/20/files Kenta's repository needs to be updated to import it though
