### ISSUE TITLE
Rename folders to make more sense

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-mapper#49]
**Is your feature request related to a problem? Please describe.**
Ephys, neuropixels, etc. are a bit generic and confusing

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mekhlakapoor** [comment]
[10:19 AM] Jon Young
- read scan image tiff vx headers (bergamo)

- read scan image tiff vy headers (mesoscope)

- read openephys logfiles

- read behavior pkl files (openscope)

- read smartspim log files

- read exaspim log files

- read behavior h5 (dynamic routing)

- read platform.json (openscope)

- read insertions.json (dynamic routing)

**Comment by mekhlakapoor** [comment]
Also, reorganize tests
