### ISSUE TITLE
Add Contributor Guidelines

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-mapper#52]
**Is your feature request related to a problem? Please describe.**
As a developer, it will be useful to know how to contribute to this repository.

**Describe the solution you'd like**
A detailed and maintained Contributor Guideline doc

**Describe alternatives you've considered**

**Additional context**

**Comment by mekhlakapoor** [comment]
- [ ] Describe how data will be organized (by acquisition machine)
        - [ ] Drop test coverage down to 80% 
        - [ ] Unit tests organization
        - [ ] If aind-data-schema needs to be upgraded for your package, open another ticket (dedicated engineer will do it) 
        - [ ] How to organize and make a feature request
