### ISSUE TITLE
Add Integration Testing Architecture

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-mapper#53]
# User story
As a developer, I want to test against larger data sets, so I can test against data that is closer to what is actually being collected.

# Acceptance criteria
- [ ] Given IAM role, uses S3FS to get input path
- [ ] Create workflow for integration tests
- [ ] 

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
Look into github LLS to store large files, then same as github actions.
Otherwise can look into how do to this using AWS.
