### ISSUE TITLE
Migrate to dev/prod structure

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-mapper#95]
**Is your feature request related to a problem? Please describe.**
It's currently not clear what's in prod vs dev. 

**Describe the solution you'd like**
It'd be useful to have a dev branch separate from main.

**Describe alternatives you've considered**

**Additional context**

**Comment by jtyoung84** [comment]
Closed by https://github.com/AllenNeuralDynamics/aind-metadata-mapper/pull/99
